### PR TITLE
Feature/public lb with eip

### PR DESCRIPTION
**Pull request by nicolas-san**
New example to test adding an EIP in a load_balancer

### CODE REVIEW

**Comment by outscale-toa** [comment]
Hello @nicolas-san 

Thanks for your contribution,
Can you please sign your commits with gpgkeys?
[here](https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits)  is the documentation to sign commits with gpgkeys.

Best Regards,

**Comment by nicolas-san** [comment]
Hi @outscale-toa 
I'll we do it today :)

**Comment by nicolas-san** [comment]
@outscale-toa any news on this ?
Could I do something else ?

**Comment by FredericBerot-Armand** [comment]
Hi @nicolas-san 

I use your idea for make an acceptance test.
I don't think we need add an example for this feature, so i close this PR.

Anyway, you have some troubles in your example.

Best regards.

**Pull request closed without merging**
